reserv = {
    "Roperacion"    :"operacion",
    "Rval1"         :"valor1",
    "Rval2"         :"valor2",
    "Rsuma"         :"suma",
    "Rresta"        :"resta",
    "Rmulti"        :"multiplicacion",
    "Rdiv"          :"division",
    "Rpotencia"     :"potencia",
    "Rraiz"         :"raiz",
    "Rinverso"      :"inverso",
    "Rsin"          :"seno",
    "Rtang"         :"tangente",
    "Rmod"          :"mod",
    "Rtxt"          :"texto",
    "RcolorNodo"    :"Color-Fondo-Nodo",
    "Rcolorfuente"  :"Color-Fuente-Nodo",
    "Rforma"        :"Forma-Nodo",
    "Fcirc"         :"circulo",
    "Ftri"          :"triangulo",
    "Frec"          :"rectangulo",
    "coma"          :",",
    "punto"         :".",
    "Dpuntos"       :":",
    "CorchIzq"      :"[",
    "CorchDer"      :"]",
    "llaveIzq"      :"{",
    "llaveDer"      :"}",

}