reserv = {
    "Roperacion"    :"Operacion",
    "Rval1"         :"Valor1",
    "Rval2"         :"Valor2",
    "Rsuma"         :"Suma",
    "Rresta"        :"Resta",
    "Rmulti"        :"Multiplicacion",
    "Rdiv"          :"Division",
    "Rpotencia"     :"Potencia",
    "Rraiz"         :"Raiz",
    "Rinverso"      :"Inverso",
    "Rsin"          :"Seno",
    "Rtang"         :"Tangente",
    "Rmod"          :"Mod",
    "Rtxt"          :"Texto",
    "RcolorNodo"    :"Color-Fondo-Nodo",
    "Rcolorfuente"  :"Color-Fuente-Nodo",
    "Rforma"        :"Forma-Nodo",
    "coma"          :",",
    "punto"         :".",
    "Dpuntos"       :":",
    "CorchIzq"      :"[",
    "CorchDer"      :"]",
    "llaveIzq"      :"{",
    "llaveDer"      :"}",
    "color0"        :"Rojo",
    "color1"        :"Verde",
    "color2"        :"Azul",
    "color3"        :"Amarillo",
    "color4"        :"Morado",
    "color5"        :"Blanco",
    "color6"        :"Gris",
    "color7"        :"Celeste",
    "color8"        :"Anaranjado",
    "color9"        :"Lila",
    "color10"       :"Negro",
    "color11"       :"Cafe",
    "color12"       :"Rosado",
    "color13"       :"Mostaza",
    "color14"       :"Cyan",
    "figura1"       :"Circulo",
    "figura2"       :"Cuadrado",
    "figura3"       :"Triangulo",
    "figura4"       :"Ovalo",
    "figura5"       :"Diamante",
    "figura6"       :"Rectangulo",
    "figura7"       :"Cilindro",
    "figura8"       :"Pentagono",
    "figura9"       :"Caja",
    "figura10"      :"Octagono",
    "figura11"      :"Estrella",
}

colors = {
    "Rojo":"#ff0000",
    "Verde":"#00854c",
    "Azul":"#003ee3",
    "Amarillo":"#ffe748",
    "Morado":"#4e1a4f",
    "Blanco":"#f8f5ff",
    "Gris":"#707070",
    "Celeste":"#11c5ff",
    "Anaranjado":"#ff6b00",
    "Lila":"#99339b",
    "Negro":"#242424",
    "Cafe":"#7c624a",
    "Rosado":"#ff54ee",
    "Mostaza":"#b29032",
    "Cyan":"#008b8b",
}

formas ={
    'Circulo':'circle',
    'Cuadrado':'square',
    'Triangulo':'triangle',
    'Ovalo':'oval',
    'Diamante':'diamond',
    'Rectangulo':'rectangle',
    'Cilindro':'cylinder',
    'Pentagono':'pentagon',
    'Caja':'box',
    'Octagono':'octagon',
    'Estrella':'star',
}