reserv = {
    "Roperacion"    :"operacion",
    "Rval1"         :"valor1",
    "Rval2"         :"valor2",
    "Rsuma"         :"suma",
    "Rresta"        :"resta",
    "Rmulti"        :"multiplicacion",
    "Rdiv"          :"division",
    "Rpotencia"     :"potencia",
    "Rraiz"         :"raiz",
    "Rinverso"      :"inverso",
    "Rsin"          :"seno",
    "Rtang"         :"tangente",
    "Rmod"          :"mod",
    "Rtxt"          :"texto",
    "RcolorNodo"    :"Color-Fondo-Nodo",
    "Rcolorfuente"  :"Color-Fuente-Nodo",
    "Rforma"        :"Forma-Nodo",
    "Fcirc"         :"circulo",
    "Ftri"          :"triangulo",
    "Frec"          :"rectangulo",
    "coma"          :",",
    "punto"         :".",
    "Dpuntos"       :":",
    "CorchIzq"      :"[",
    "CorchDer"      :"]",
    "llaveIzq"      :"{",
    "llaveDer"      :"}",

}

colors = {
    "Rojo":"#ff0000",
    "Verde":"#00854c",
    "Azul":"#003ee3",
    "Amarillo":"#ffe748",
    "Morado":"#4e1a4f",
    "Blanco":"#f8f5ff",
    "Gris":"#707070",
    "Celeste":"#11c5ff",
    "Anaranjado":"#ff6b00",
    "Lila":"#99339b",
    "Negro":"#242424",
    "Cafe":"#7c624a",
    "Rosado":"#ff54ee",
    "Mostaza":"#b29032",
    "Cyan":"#008b8b",
}

formas ={
    'Circulo':'circle',
    'Cuadrado':'square',
    'Triangulo':'triangle',
    'Ovalo':'oval',
    'Diamante':'diamond',
    'Rectangulo':'rectangle',
    'Cilindro':'cylinder',
    'Pentagono':'pentagon',
    'Caja':'box',
    'Octagono':'octagon',
    'Estrella':'star',

}